spring:
  application:
    name: TestWebApp
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: grozny2005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081